### ISSUE TITLE
Question about Map<String, String> for row

### ISSUE THREAD

**Issue by FilledStacks** [synw/sqlcool#28]
Hi there,

Why is it that a DB row has to be a `Map<String, String>`. I'm having quite a bit of a problem serialising to and from the actual value and knowing which values were int's before I put them into the DB. 

I'm reverting back to using the database on it's own but I was wondering if you had a particular reason? 

Also how do you currently know to convert to and form an integer if the value that goes in it a null value. I'm using freezed and json serialize to generate my models I'm not writing them by hand.

**Comment by synw** [comment]
I went for strings map because anyway it will end up as a string when writing: I wanted to delegate the type conversions to the user. But I know this is not optimal: this is why I made a type safe api for version 5.0.0 to come: I'm looking for feedback on this before freezing the api and releasing: https://github.com/synw/sqlcool/issues/26 

> if the value that goes in it a null value

Actually the user is responsible for the null checks in the serializer/deserializer

**Comment by FilledStacks** [comment]
@synw You're right about the user being responsible for that. It's just some additional overhead with the storing and reading especially when you generate all your models json serialisation. I've written some converters that takes null into account. I was just curios to how you'll handle it. 

Thanks for answering me.
